# Generated by Django 3.1.6 on 2021-11-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test1', '0002_auto_20211116_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksrecord',
            name='sold_at',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
